file_downloader.download_option_config.*:
  type: config_entity
  label: 'Download option config config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin_id:
      type: string
      label: 'Plugin'
    extensions:
      type: string
      label: 'Extensions'
    settings:
          type: icon_set.settings.[%parent.plugin]